### ISSUE TITLE
Consider replacing ParseEnv with envconfig

### ISSUE THREAD

**Issue by DallanQ** [OurRootsOrg/cms-server#14]
This library parses environment variables automatically into a struct

https://github.com/kelseyhightower/envconfig

**Comment by jancona** [comment]
I already switched to this library on my branch: https://pkg.go.dev/github.com/codingconcepts/env
Any strong perference for the other one?

**Comment by DallanQ** [comment]
It turns out no. envconfig automatically populates the Env struct from the environment, but it wasn't as much of a win as I had hoped because you still need to do the validations. See PR #16
