### ISSUE TITLE
Add support for places to DynamoDB

### ISSUE THREAD

**Issue by DallanQ** [OurRootsOrg/cms-server#55]

**Comment by DallanQ** [comment]
Copy comments from #53 

* SelectPlaceSettings - just 1 row, easy
 * SelectPlace and SelectPlacesByID - key-value lookup, should be easy
* SelectPlaceWord and SelectPlaceWordsByWord - key-value lookup, should be easy
* SelectPlacesByFullNamePrefix - this is the challenging one. It's for auto-complete, so if someone enters "Main" they'll get back "Maine, United States", "Maine, France", and "Maineville, Warren, Ohio, United States". The WHERE clause is a case-insensitive LIKE. And query results are sorted by a "count" field which indicates the general popularity of the place, so that Maine, United States appears above Maineville, Ohio and the top N are returned. One way to do it would be to put all 500k placenames in the same partition, do the LIKE on the sort key, and then to read all results (up to say a reasonable number) and return the N results with the highest "count" values manually. Any other ideas?

@jancona For your fourth bullet, the other way to partition is by the first letter or first two letters. As long as you don't care about being able to search on one letter, you can put "Maine, United States", "Maine, France", and "Maineville, Warren, Ohio, United States" in the "MA" partition. That way you have 500k places in 26^2 partitions, so the partitions aren't so large or hot.

**Comment by jancona** [comment]
Fixed by #91
