### ISSUE TITLE
Consider separate PostStatus, RecordsStatus, and ImagesStatus fields on Posts

### ISSUE THREAD

**Issue by DallanQ** [OurRootsOrg/cms-server#79]
Currently the RecordsStatus records whether the post is in draft, published, publishing, or unpublishing, and also whether records are loading. And the ImagesStatus records whether images are loading. But this is a bit confusing, because when RecordsStatus is Draft and ImagesStatus is Loading, we really mean that the Post is in Draft status, the records may or may not have been loaded yet, and images are loading. Also, ImagesStatus is Draft whether or not images have been loaded. Finally, if the record load or images load has an error, we have no way to tell the user that all did not go well. As far as the user can tell, the records/images loaded successfully because the corresponding status is in Draft again. 

It seems like it would be clearer to have the following fields:
* PostStatus: Draft, Published, Publishing, Unpublishing
* RecordsStatus: empty string (initial state), Loading, Error // if the load is successful, Status is set to empty
* ImagesStatus: empty string (initial state), Loading, Error // if the load is successful, Status is set to empty
* RecordsError: contains the error message if RecordsStatus is Error (or the error message could be put into the RecordsStatus field)
* ImagesError: contains the error message if ImagesStatus is Error (or the error message could be put into the ImagesStatus field)

@jancona What do you think? This is likely a breaking change, but I could create a new migrations.up file with a SQL update statement to update the existing posts to the new format.

**Comment by jancona** [comment]
I always find this kind of thing to be confusing when doing maintenance and a source of obscure bugs. Your proposal sounds like an improvement. Perhaps you could draw up a state machine with the legal transitions and put it somewhere, or at least put the above in a comment.

**Comment by DallanQ** [comment]
Good idea. I'll add a long comment in model explaining everything, including a state machine.

**Comment by DallanQ** [comment]
Handled by #83
