### ISSUE TITLE
DynamoDB persistence

### ISSUE THREAD

**Issue by DallanQ** [OurRootsOrg/cms-server#84]
Support for the following tables needs to be added to DynamoDB
* givenname_variants and surname_variants
* place_settings, places, and place_words
* record_household

**Comment by jancona** [comment]
When all of the following PRs are merged, this will be complete:
* givenname_variants and surname_variants - #96
* place_settings, places, and place_words - #91, #95
* record_household - #94

**Comment by jancona** [comment]
All the above are merged.
